---
- name: filebeat
  hosts: host
  become: yes
  become_method: sudo
  remote_user: user
  tasks:
    - name: apt update
      ansible.builtin.shell:
        apt update

    - name: Install elasticsearch repository
      ansible.builtin.shell: |
        wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch &&
        echo "deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/7/ stable main" | sudo tee /etc/apt/sources.list.d/elastic-7.x.list &&
        apt update

    - name: install filebeat
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - filebeat

    - name: filebeat enable
      ansible.builtin.shell: |
        systemctl daemon-reload &&
        systemctl enable filebeat.service &&
        systemctl start filebeat.service

    - name:  Configure 
      ansible.builtin.shell: |
        filebeat modules list &&
        filebeat modules enable system nginx &&
        sed -i 's/    - \x2Fvar\x2Flog\x2F\*.log/    - \x2Fvar\x2Flog\x2Fnginx\x2Faccess.log\n    - \x2Fvar\x2Flog\x2Fnginx\x2Ferroe.log/g' /etc/filebeat/filebeat.yml &&
        sed -i 's/localhost:9200/158.160.41.107:9200/g' /etc/filebeat/filebeat.yml &&
        systemctl restart filebeat
