---
- name: ZabbixAgent
  hosts: host
  become: yes
  become_method: sudo
  remote_user: user
  tasks:
    - name: apt update
      ansible.builtin.shell:
        sudo apt update

    - name: Install Zabbix repository
      ansible.builtin.shell: |
        wget https://repo.zabbix.com/zabbix/7.2/release/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.2+ubuntu24.04_all.deb &&
        dpkg -i zabbix-release_latest_7.2+ubuntu24.04_all.deb &&
        apt update

    - name: Install Zabbix agent
      ansible.builtin.apt:
        name: zabbix-agent
        state: latest

    - name:  Configure the database for Zabbix server and PHP for Zabbix frontend
      ansible.builtin.shell: |
        sed -i 's/Server=127.0.0.1/Server=89.169.135.78/g' /etc/zabbix/zabbix_agentd.conf

    - name: Start Zabbix agent and agent processes
      ansible.builtin.shell: |
        systemctl restart zabbix-agent
        systemctl enable zabbix-agent
        
